name: Python Package
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.x"
          enable-cache: true

      - name: Verify version matches in code and release
        run: |
          VER=$(uv run python -c 'import bcpandas; print(bcpandas.__version__)')
          CLEAN_RELEASE_VAR=${RELEASE_VAR#v}
          if [[ $VER != $CLEAN_RELEASE_VAR ]]; then
            echo "version $VER does not match released version $CLEAN_RELEASE_VAR, needs a bump!" && exit 1
          fi
        env:
          RELEASE_VAR: ${{ github.event.release.tag_name }}

      - name: Build and publish
        run: |
          uv build
          uv publish \
            --username "${{ secrets.PYPI_USERNAME }}" \
            --password "${{ secrets.PYPI_PASSWORD }}"
